### ISSUE TITLE
the same model gives different answers

### ISSUE THREAD

**Issue by IvanPy96** [yafuly/DeepfakeTextDetect#10]
Hi!
I can't understand why the same model gives different answers. 
Here's an example:
"Apples are crisp, juicy fruits that belong to the Rosaceae family and are widely cultivated around the world. Known scientifically as Malus domestica, apples come in a variety of colors, including red, green, and yellow, each offering a distinct flavor profile. Renowned for their sweet taste and versatility, apples are not only enjoyed as a delightful snack but also used in a multitude of culinary applications."
If you run it online, the answer of the model is "machine-generated", which is true, I generated this text with GPT3.5.
But if you run it locally with 

import torch
import os
from transformers import AutoModelForSequenceClassification,AutoTokenizer

device = 'cpu' 
model_dir = "nealcly/detection-longformer"
tokenizer = AutoTokenizer.from_pretrained(model_dir)
model = AutoModelForSequenceClassification.from_pretrained(model_dir).to(device)

text = example
text = preprocess(text)
result = detect(text,tokenizer,model,device)

the answer is "human-written".
Why is that? And how do I download the online version of a good model locally?

**Comment by yafuly** [comment]
Hi,

The model we uploaded to the Huggingface page corresponds to the one described in our paper, distinct from the demo model. We will soon upload the demo model to the Huggingface page.

**Comment by IvanPy96** [comment]
Thanks, I'll wait!

**Comment by yafuly** [comment]
Hi,

We've uploaded the demo model which can be accessed via [yaful/DeepfakeTextDetection](https://huggingface.co/yaful/DeepfakeTextDetection).

**Comment by IvanPy96** [comment]
Thank you so much! And the last question: are function for preprocess and detect the same in previous version? And threshold th=-3.08583984375 the same?

**Comment by yafuly** [comment]
Yes, all settings remain the same.
