### ISSUE TITLE
Text Generation Parameters

### ISSUE THREAD

**Issue by AvantiB** [yafuly/DeepfakeTextDetect#12]
Hi,

Thanks for releasing this dataset. I just wanted to know what were the parameters used for generation. Since you mentioned using HuggingFace for generation for all open-source models, if you could please list generation parameters (https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.GenerationConfig), it would be great. Additionally, openAI API also requires parameter definition for temperature/top-p. did you specify any or use the default setting?
Thanks

Best,
Avanti

**Comment by yafuly** [comment]
Hi Avanti,

Thanks for following our work.

For API-based models, we use the default decoding parameters. For other LLMs (Huggingface), we adopt the following parameters:
```
    --max_new_tokens 1024 \
    --top_p 1.0 \
    --top_k 0 \
    --temperature 0.7 \
```
