### ISSUE TITLE
Paraphrased generated texts aren't classifying as Machine-generated

### ISSUE THREAD

**Issue by maitri-vv** [yafuly/DeepfakeTextDetect#13]
I came across your project while doing my ongoing final year major project of detecting fake news. Well! I must appreciate the different unique approach of your project 💯 .  However, I tested your online lived webpage but seems that it isnt detecting correctly if the text is paraphrased. Also if some 'human' changes some words or sentences or for that matter even a paragraph in a Machine-generated text; how is the whole thing still being classified as Machine generated? 
Would love to have insights on these for improving it :)

**Comment by yafuly** [comment]
Hi,

Thanks for following our work. Yes, the text-level detection system can be vulnerable to attacks such as paraphrasing and local work modifications. One simple solution is to involve such training data (e.g., AI paraphrases) in the model training phase.

You can refer to this paper for other solutions:
[Paraphrasing evades detectors of AI-generated text, but retrieval is an effective defense](https://arxiv.org/abs/2303.13408)
