### ISSUE TITLE
Some questions about reported metrics

### ISSUE THREAD

**Issue by sweetdream779** [yafuly/DeepfakeTextDetect#14]
Hello, thank you for your work!

I have some clarification questions about your reported metrics:

- In case of out-of-distribution evaluations, you trained several models with different subsets and reported "their weighted average performance." But which weights did you use or how can I calculate them?
- In case of Wilder Testsets evaluation, did you use your general classifier which were trained on Arbitrary-domains & Arbitrary-models data(Testbed 4)?

Thanks!

**Comment by yafuly** [comment]
Hi,

- "weighted average performance" means weighting the performance by the size of the testset.
- Yes, the classifier was trained on "Arbitrary-domains & Arbitrary-models data", with the decision boundary adjusted.

Thank you for your interest in our work. Please feel free to reach out with any additional questions.

**Comment by sweetdream779** [comment]
Thanks for the answer!
One more clarification question about weighting. Am I calculating the weights correctly?
```
sizes = np.array([[7420, 5386, 9320, 1838, 13284, 2884, 16024]])
weights = sizes / np.sum(sizes)
```

**Comment by yafuly** [comment]
Yes, your calculation of the weights is correct.

**Comment by sweetdream779** [comment]
Thank you!
