### ISSUE TITLE
Question for the settings of generate function

### ISSUE THREAD

**Issue by BUPT-tyf** [yafuly/DeepfakeTextDetect#15]
Thank you very much for publishing the relevant dataset. However, I am unable to restore the dataset published by the author according to your settings. There seem to be some issues with the quality of the dataset. Could the author provide the specific code, including the settings for the generate function.

**Comment by yafuly** [comment]
Hi,

Regrettably, we did not preserve the original generation files and configurations. At that time, the lack of a robust inference framework such as VLLM necessitated the use of various codes for text generation across different LLMs, complicating exact reproduction. The default settings for temperature and top_p were 0.7 and 0.95, respectively.

**Comment by yafuly** [comment]
Feel free to reopen the issue if you have further questions.
