### ISSUE TITLE
Asking some question about Longformer

### ISSUE THREAD

**Issue by qing0518** [yafuly/DeepfakeTextDetect#2]
Hi, I am very interested in your research, But I have one more question to ask you. You have constructed many datasets for training and testing, and then provided a classifier for Longformer. What I would like to ask is, in which type of dataset did you provide training for this Longformer (for example: unseen_domains or unseen_models or else)?
Also, could you please provide URLs to other models that appear in your paper?
Thanks！

**Comment by yafuly** [comment]
Hi,

Thank you for your interest in our research. We've trained the Longformer model utilizing the full dataset (i.e., cross-domains and cross-models). The decision boundary was subsequently refined based on our Out-of-Domain (OOD) experimentation.

Our study encompassed a large set of models, amounting to a total of 29. Given the constraints associated with cloud storage, we regret to inform you that we will not be able to release all of these models.

If you have any further inquiries about using our data, please do not hesitate to contact us.
