### ISSUE TITLE
`deployment/cleantext.py` is missing

### ISSUE THREAD

**Issue by Yorko** [yafuly/DeepfakeTextDetect#3]
Apparently, [this import](https://github.com/yafuly/DeepfakeTextDetect/blob/main/deployment/utils.py#L3) implies there is a file `deployment/cleantext.py`. However, this file is not committed. Thus, formally, the [Model Access](https://github.com/yafuly/DeepfakeTextDetect/tree/main#model-access) part of Readme is irreproducible.

**Comment by yafuly** [comment]
Hi,

Thank you for bringing the confusion to my attention. The "cleantext" function is part of a Python package that can be installed by running the following command:

```shell
pip install clean-text
```

We will also provide a "requirements.txt" file that includes all necessary dependencies.

**Comment by Yorko** [comment]
Thanks, it works now.
