### ISSUE TITLE
Maybe a typo on page 5

### ISSUE THREAD

**Issue by jeremy-feng** [yafuly/DeepfakeTextDetect#5]
On page 5 of your paper:

> This process creates 10 testbeds for cross-validation. We train 7 classifiers for each testbed and report their weighted average performance.

I think it should be `10 classifiers for each testbed` instead of `7`.

<img width="639" alt="image" src="https://github.com/yafuly/DeepfakeTextDetect/assets/44312563/df27cccf-47e5-417a-8188-131911e2b69a">

**Comment by yafuly** [comment]
Hi,

Thanks for your contribution! You're right. We will fix this typo in our next version.
