### ISSUE TITLE
Local dependencies in requirements.txt

### ISSUE THREAD

**Issue by 4turkuaz** [yafuly/DeepfakeTextDetect#6]
Hi,

There are some local dependencies in the **requirements.txt**:

1. cffi @ file:///tmp/build/80754af9/cffi_1625807838443/work
2. chardet @ file:///tmp/build/80754af9/chardet_1607706746162/work
3. conda-package-handling @ file:///tmp/build/80754af9/conda-package-handling_1618262148928/work
4. cryptography @ file:///tmp/build/80754af9/cryptography_1616769286105/work
5. idna @ file:///home/linux1/recipes/ci/idna_1610986105248/work
6. pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
7. pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
8. PySocks @ file:///tmp/build/80754af9/pysocks_1605305779399/work
9. ruamel-yaml-conda @ file:///tmp/build/80754af9/ruamel_yaml_1616016699510/work
10. six @ file:///tmp/build/80754af9/six_1623709665295/work
11. urllib3 @ file:///tmp/build/80754af9/urllib3_1625084269274/work

Therefore running the command `pip install -r requirements.txt` raises exceptions such as `ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/build/80754af9/cffi_1625807838443/work'`. 

I guess that either the file needs to be fixed manually or re-generated using some external packages such as [pipreqs](https://github.com/bndr/pipreqs). 

Thanks.

**Comment by Linzwcs** [comment]
> Hi,
> 
> There are some local dependencies in the **requirements.txt**:
> 
> 1. cffi @ file:///tmp/build/80754af9/cffi_1625807838443/work
> 2. chardet @ file:///tmp/build/80754af9/chardet_1607706746162/work
> 3. conda-package-handling @ file:///tmp/build/80754af9/conda-package-handling_1618262148928/work
> 4. cryptography @ file:///tmp/build/80754af9/cryptography_1616769286105/work
> 5. idna @ file:///home/linux1/recipes/ci/idna_1610986105248/work
> 6. pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
> 7. pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
> 8. PySocks @ file:///tmp/build/80754af9/pysocks_1605305779399/work
> 9. ruamel-yaml-conda @ file:///tmp/build/80754af9/ruamel_yaml_1616016699510/work
> 10. six @ file:///tmp/build/80754af9/six_1623709665295/work
> 11. urllib3 @ file:///tmp/build/80754af9/urllib3_1625084269274/work
> 
> Therefore running the command `pip install -r requirements.txt` raises exceptions such as `ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/build/80754af9/cffi_1625807838443/work'`.
> 
> I guess that either the file needs to be fixed manually or re-generated using some external packages such as [pipreqs](https://github.com/bndr/pipreqs).
> 
> Thanks.

I have resolved this issue. Is it correct now？

**Comment by 4turkuaz** [comment]
For macOS with Python version 3.9.15 and pip version 23.3.1, it raises exceptions for:

- torch==1.13.1+cu116
- torchaudio==0.13.1+cu116
- torchvision==0.14.1+cu116


since they are the Linux/Windows distributions. Removing `+cu116` parts resolved the issue.
