### ISSUE TITLE
How is the value of "th" obtained in the detect function?

### ISSUE THREAD

**Issue by inanb** [yafuly/DeepfakeTextDetect#9]
Hello, I'm a beginner and this question might be simple, but I'm really curious about how the value of "th"is calculated. It would be great if you could provide an answer. 

`def detect(input_text, tokenizer, model, device='cuda:0', th=-3.08583984375):`

**Comment by yafuly** [comment]
Hi,

You can refer to our [paper](https://arxiv.org/abs/2305.13242) for a detailed explanation of boundary adjustment, specifically in Section 5.3 under the paragraph titled "Boundary reselection."

**Comment by inanb** [comment]
Hello,

Thank you very much for your detailed explanation.

I have a question regarding the original text, "We average the decision boundary across 10 classifiers and use it for all domains." Can I understand it as you training different classifiers in 10 domains, and then using some method to average this classification boundary?

Below is the internal implementation of LongformerForSequenceClassification and the actual structure of the trained model:




```
class LongformerClassificationHead(nn.Module):
    """Head for sentence-level classification tasks."""

    def __init__(self, config):
        super().__init__()
        self.dense = nn.Linear(config.hidden_size, config.hidden_size)
        self.dropout = nn.Dropout(config.hidden_dropout_prob)
        self.out_proj = nn.Linear(config.hidden_size, config.num_labels)

    def forward(self, hidden_states, **kwargs):
        hidden_states = hidden_states[:, 0, :]  # take <s> token (equiv. to [CLS])
        hidden_states = self.dropout(hidden_states)
        hidden_states = self.dense(hidden_states)
        hidden_states = torch.tanh(hidden_states)
        hidden_states = self.dropout(hidden_states)
        output = self.out_proj(hidden_states)
        return output

(classifier): LongformerClassificationHead(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (out_proj): Linear(in_features=768, out_features=2, bias=True)
  )
```
  


My confusion is that, I don't seem to see how the decision boundary is obtained. I also saw the Default Boundary in figure 7, so I would like to ask how these boundaries are obtained.

Thank you for your time❤.

**Comment by yafuly** [comment]
Hi,

Yes, your understanding ("Can I understand it as you training different classifiers in 10 domains, and then using some method to average this classification boundary") is correct.

Typically, a small amount of in-domain validation can yield an 'optimized' boundary for that domain. Here is a sample code for obtaining the optimized decision boundary:
```python
from sklearn.metrics import roc_curve
def _eval_db(scores, refs):    
    # find threshold
    fpr, tpr, thresholds = roc_curve(refs, scores)
    J = tpr - fpr
    idx = np.argmax(J)
    optimal_threshold = thresholds[idx]
    print(f"ths:{optimal_threshold}")
```

Next, the average of the 10 boundaries for each domain is computed to obtain the final boundary.
